export default {
    stocks: [
        {
            ticker: 'NVDA',
            name: 'NVIDIA Corporation',
            currentPrice: 190.53,
            logoUrl: 'logos/stocks/nvidia.png',
        },
        {
            ticker: 'SAP.DE',
            name: 'SAP SE',
            currentPrice: 207.7,
            logoUrl: 'logos/stocks/sap.png',
        },
        {
            ticker: 'ADS.DE',
            name: 'adidas AG',
            currentPrice: 164.4,
            logoUrl: 'logos/stocks/adidas.png',
        },
        {
            ticker: 'INTC',
            name: 'Intel Corporation',
            currentPrice: 36.2,
            logoUrl: 'logos/stocks/intel.png',
        },
        {
            ticker: 'NFLX',
            name: 'Netflix, Inc.',
            currentPrice: 94.47,
            logoUrl: 'logos/stocks/netflix.png',
        },
        {
            ticker: 'AMZN',
            name: 'Amazon.com, Inc.',
            currentPrice: 232.52,
            logoUrl: 'logos/stocks/amazon.png',
        },
        {
            ticker: 'AAPL',
            name: 'Apple Inc.',
            currentPrice: 273.4,
            logoUrl: 'logos/stocks/apple.png',
        },
        {
            ticker: 'VOW3.DE',
            name: 'Volkswagen AG',
            currentPrice: 103.75,
            logoUrl: 'logos/stocks/volkswagen.png',
        },
        {
            ticker: 'GOOGL',
            name: 'Alphabet Inc.',
            currentPrice: 313.51,
            logoUrl: 'logos/stocks/alphabet.png',
        },
        {
            ticker: 'DIS',
            name: 'The Walt Disney Company',
            currentPrice: 113.56,
            logoUrl: 'logos/stocks/disney.png',
        },
        {
            ticker: 'PG',
            name: 'The Procter & Gamble Company',
            currentPrice: 144.74,
            logoUrl: 'logos/stocks/p&g.png',
        },
        {
            ticker: 'BABA',
            name: 'Alibaba Group Holding Limited',
            currentPrice: 152.24,
            logoUrl: 'logos/stocks/alibaba.png',
        },
        {
            ticker: 'CSCO',
            name: 'Cisco Systems, Inc.',
            currentPrice: 78.16,
            logoUrl: 'logos/stocks/cisco.png',
        },
        {
            ticker: 'ZAL.DE',
            name: 'Zalando SE',
            currentPrice: 24.92,
            logoUrl: 'logos/stocks/zalando.png',
        },
        {
            ticker: 'ORCL',
            name: 'Oracle Corporation',
            currentPrice: 197.99,
            logoUrl: 'logos/stocks/oracle.png',
        },
        {
            ticker: 'LMT',
            name: 'Lockheed Martin Corporation',
            currentPrice: 483.03,
            logoUrl: 'logos/stocks/lockheed_martin.png',
        },
        {
            ticker: 'BMW.DE',
            name: 'Bayerische Motoren Werke Aktiengesellschaft',
            currentPrice: 92.66,
            logoUrl: 'logos/stocks/bmw.png',
        },
        {
            ticker: 'JPM',
            name: 'JPMorgan Chase & Co.',
            currentPrice: 327.91,
            logoUrl: 'logos/stocks/jpmorgan_chase.png',
        },
        {
            ticker: 'MSFT',
            name: 'Microsoft Corporation',
            currentPrice: 487.71,
            logoUrl: 'logos/stocks/microsoft.png',
        },
        {
            ticker: 'TSLA',
            name: 'Tesla, Inc.',
            currentPrice: 475.19,
            logoUrl: 'logos/stocks/tesla.png',
        },
        {
            ticker: 'META',
            name: 'Meta Platforms, Inc.',
            currentPrice: 663.29,
            logoUrl: 'logos/stocks/meta.png',
        },
    ],
    etfs: [
        {
            ticker: 'QQQ',
            name: 'Invesco QQQ Trust',
            currentPrice: 623.89,
            logoUrl: 'logos/etfs/qqq.png',
        },
        {
            ticker: 'SLV',
            name: 'iShares Silver Trust',
            currentPrice: 71.12,
            logoUrl: 'logos/etfs/slv.png',
        },
        {
            ticker: 'GLD',
            name: 'SPDR Gold Shares',
            currentPrice: 416.74,
            logoUrl: 'logos/etfs/gld.png',
        },
        {
            ticker: 'IWM',
            name: 'iShares Russell 2000 ETF',
            currentPrice: 251.42,
            logoUrl: 'logos/etfs/iwm.png',
        },
        {
            ticker: 'VTI',
            name: 'Vanguard Total Stock Market Index Fund ETF Shares',
            currentPrice: 339.67,
            logoUrl: 'logos/etfs/vti.png',
        },
        {
            ticker: 'DIA',
            name: 'SPDR Dow Jones Industrial Average ETF Trust',
            currentPrice: 487.03,
            logoUrl: 'logos/etfs/dia.png',
        },
        {
            ticker: 'SPY',
            name: 'SPDR S&P 500 ETF',
            currentPrice: 690.31,
            logoUrl: 'logos/etfs/spy.png',
        },
        {
            ticker: 'EEM',
            name: 'iShares MSCI Emerging Markets ETF',
            currentPrice: 54.8,
            logoUrl: 'logos/etfs/eem.png',
        },
        {
            ticker: 'EXI',
            name: 'iShares Global Industrials ETF',
            currentPrice: 176.9,
            logoUrl: 'logos/etfs/exi2.png',
        },
        {
            ticker: 'VNQ',
            name: 'Vanguard Real Estate Index Fund ETF Shares',
            currentPrice: 88.86,
            logoUrl: 'logos/etfs/vnq.png',
        },
    ],
    commodities: [
        {
            ticker: 'ZW=F',
            name: 'Chicago SRW Wheat Futures,Mar-2',
            currentPrice: 519,
            logoUrl: 'logos/commodities/wheat.png',
        },
        {
            ticker: 'ZS=F',
            name: 'Soybean Futures,Mar-2026',
            currentPrice: 1072.5,
            logoUrl: 'logos/commodities/soybeans.png',
        },
        {
            ticker: 'KC=F',
            name: 'KC=F',
            currentPrice: 345.15,
            logoUrl: 'logos/commodities/coffee.png',
        },
        {
            ticker: 'CT=F',
            name: 'Cotton Mar 26',
            currentPrice: 63.8,
            logoUrl: 'logos/commodities/cotton.png',
        },
        {
            ticker: 'SI=F',
            name: 'Silver Mar 26',
            currentPrice: 77.196,
            logoUrl: 'logos/commodities/silver.png',
        },
        {
            ticker: 'CC=F',
            name: 'Cocoa Mar 26',
            currentPrice: 5966,
            logoUrl: 'logos/commodities/cocoa.png',
        },
        {
            ticker: 'SB=F',
            name: 'Sugar #11 May 26',
            currentPrice: 15.29,
            logoUrl: 'logos/commodities/sugar.png',
        },
        {
            ticker: 'PL=F',
            name: 'Platinum Jan 26',
            currentPrice: 2491.1,
            logoUrl: 'logos/commodities/platinum.png',
        },
        {
            ticker: 'PA=F',
            name: 'Palladium Mar 26',
            currentPrice: 2023.3,
            logoUrl: 'logos/commodities/palladium.png',
        },
        {
            ticker: 'GC=F',
            name: 'Gold Feb 26',
            currentPrice: 4552.7,
            logoUrl: 'logos/commodities/gold.png',
        },
        {
            ticker: 'NG=F',
            name: 'Natural Gas Jan 26',
            currentPrice: 3.877,
            logoUrl: 'logos/commodities/natural_gas.png',
        },
        {
            ticker: 'CL=F',
            name: 'Crude Oil Feb 26',
            currentPrice: 56.74,
            logoUrl: 'logos/commodities/oil.png',
        },
        {
            ticker: 'ZC=F',
            name: 'Corn Futures,Mar-2026',
            currentPrice: 450,
            logoUrl: 'logos/commodities/corn.png',
        },
        {
            ticker: 'HG=F',
            name: 'Copper Mar 26',
            currentPrice: 5.8395,
            logoUrl: 'logos/commodities/copper.png',
        },
    ],
    crypto: [
        {
            ticker: 'BTC-USD',
            name: 'Bitcoin USD',
            currentPrice: 87564.586,
            logoUrl: 'logos/crypto/btc.png',
        },
        {
            ticker: 'DOT-USD',
            name: 'Polkadot USD',
            currentPrice: 1.7449228,
            logoUrl: 'logos/crypto/dot.png',
        },
        {
            ticker: 'LTC-USD',
            name: 'Litecoin USD',
            currentPrice: 77.33496,
            logoUrl: 'logos/crypto/ltc.png',
        },
        {
            ticker: 'SOL-USD',
            name: 'Solana USD',
            currentPrice: 123.01831,
            logoUrl: 'logos/crypto/sol.png',
        },
        {
            ticker: 'XRP-USD',
            name: 'XRP USD',
            currentPrice: 1.8523238,
            logoUrl: 'logos/crypto/xrp.png',
        },
        {
            ticker: 'DOGE-USD',
            name: 'Dogecoin USD',
            currentPrice: 0.122625366,
            logoUrl: 'logos/crypto/doge.png',
        },
        {
            ticker: 'ADA-USD',
            name: 'Cardano USD',
            currentPrice: 0.3536616,
            logoUrl: 'logos/crypto/ada.png',
        },
        {
            ticker: 'ETH-USD',
            name: 'Ethereum USD',
            currentPrice: 2934.106,
            logoUrl: 'logos/crypto/eth.png',
        },
    ],
};
